[package]
name = "experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
regex = "1.7.1"
async-std = "1"
tokio = { version = "1.26.0", features = ["full"] }
fxhash = "0.2.1"
libflate = "2.0.0"
worker = "0.0.18"
